### ISSUE TITLE
Install next-auth EdgeDB adapter 

### ISSUE THREAD

**Issue by MiroslavPetrik** [PastelStoic/create-t3-edgedb-app#1]
Hello,

The custom  EdgeDB adapter can be replaced with soon to be official next-auth adapter:
https://github.com/nextauthjs/next-auth/pull/5781

Currently can be installed from `@bruno_crosier/edgedb-adapter` instead of `next-auth/edgedb-adapter`.

The pros are that its test coverage, and pushes the code out of project into library space.

**Comment by PastelStoic** [comment]
Done! Sorry for being late.
